"""Add vendor compliance metrics fields

Revision ID: 02de63d3577d
Revises: a2f4fd69bcbc
Create Date: 2025-12-02 04:03:10.870839+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02de63d3577d'
down_revision = 'a2f4fd69bcbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('compliance_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # Add with default value first, then set not null
    op.add_column('vendors', sa.Column('compliant_controls', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('vendors', sa.Column('non_compliant_controls', sa.Integer(), nullable=True, server_default='0'))
    # Set NOT NULL after setting defaults
    op.alter_column('vendors', 'compliant_controls', nullable=False)
    op.alter_column('vendors', 'non_compliant_controls', nullable=False)
    op.add_column('vendors', sa.Column('last_compliance_check', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'last_compliance_check')
    op.drop_column('vendors', 'non_compliant_controls')
    op.drop_column('vendors', 'compliant_controls')
    op.drop_column('vendors', 'compliance_rate')
    # ### end Alembic commands ###