"""Add exception model enums and table

Revision ID: cf2a725c5e10
Revises: cad7da68f813
Create Date: 2025-11-28 10:07:38.854770+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2a725c5e10'
down_revision = 'cad7da68f813'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###