"""Add activity logs table for general updates tracking

Revision ID: c0dc79dc8a00
Revises: 8a1a0b74c828
Create Date: 2025-12-30 05:08:41.618228+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c0dc79dc8a00'
down_revision = '8a1a0b74c828'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('APPLICATION_CREATED', 'APPLICATION_UPDATED', 'APPLICATION_DELETED', 'VENDOR_CREATED', 'VENDOR_UPDATED', 'VENDOR_DELETED', 'CERTIFICATE_ADDED', 'CERTIFICATE_UPDATED', 'CERTIFICATE_EXPIRED', 'CERTIFICATE_EXPIRING_SOON', 'VULNERABILITY_CREATED', 'VULNERABILITY_UPDATED', 'VULNERABILITY_CLOSED', 'VULNERABILITY_REOPENED', 'COMPLIANCE_CHECK_COMPLETED', 'COMPLIANCE_STATUS_CHANGED', 'EXCEPTION_CREATED', 'EXCEPTION_APPROVED', 'EXCEPTION_REJECTED', 'EXCEPTION_EXPIRED', 'EOSL_ASSET_ADDED', 'EOSL_ASSET_EXPIRED', 'EOSL_ASSET_EXPIRING_SOON', 'USER_LOGIN', 'USER_CREATED', 'USER_UPDATED', 'AUDIT_COMPLETED', 'AUDIT_FAILED', 'SYSTEM_ALERT', 'DATA_EXPORT', 'REPORT_GENERATED', name='activitytype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='activitypriority'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Activity log for system-wide event tracking and audit trail'
    )
    op.create_index(op.f('ix_activity_logs_activity_type'), 'activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_priority'), 'activity_logs', ['priority'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('application_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_reminders_id'), 'application_reminders', ['id'], unique=False)
    op.alter_column('vendor_certificates', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'PENDING', 'EXCEPTION', 'NOT_APPLICABLE', name='compliancestatus'),
               existing_nullable=False)
    op.alter_column('vendor_certificates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.alter_column('vendor_certificates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_index('idx_vendor_certificates_application_id', table_name='vendor_certificates')
    op.drop_index('idx_vendor_certificates_expiry_date', table_name='vendor_certificates')
    op.drop_index('idx_vendor_certificates_status', table_name='vendor_certificates')
    op.drop_index('idx_vendor_certificates_vendor_id', table_name='vendor_certificates')
    op.create_index(op.f('ix_vendor_certificates_id'), 'vendor_certificates', ['id'], unique=False)
    op.drop_constraint('vendor_certificates_application_id_fkey', 'vendor_certificates', type_='foreignkey')
    op.drop_constraint('vendor_certificates_vendor_id_fkey', 'vendor_certificates', type_='foreignkey')
    op.create_foreign_key(None, 'vendor_certificates', 'applications', ['application_id'], ['id'])
    op.create_foreign_key(None, 'vendor_certificates', 'vendors', ['vendor_id'], ['id'])
    op.alter_column('vendors', 'compliant_controls',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vendors', 'non_compliant_controls',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'non_compliant_controls',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('vendors', 'compliant_controls',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'vendor_certificates', type_='foreignkey')
    op.drop_constraint(None, 'vendor_certificates', type_='foreignkey')
    op.create_foreign_key('vendor_certificates_vendor_id_fkey', 'vendor_certificates', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('vendor_certificates_application_id_fkey', 'vendor_certificates', 'applications', ['application_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_vendor_certificates_id'), table_name='vendor_certificates')
    op.create_index('idx_vendor_certificates_vendor_id', 'vendor_certificates', ['vendor_id'], unique=False)
    op.create_index('idx_vendor_certificates_status', 'vendor_certificates', ['status'], unique=False)
    op.create_index('idx_vendor_certificates_expiry_date', 'vendor_certificates', ['expiry_date'], unique=False)
    op.create_index('idx_vendor_certificates_application_id', 'vendor_certificates', ['application_id'], unique=False)
    op.alter_column('vendor_certificates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('vendor_certificates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('vendor_certificates', 'status',
               existing_type=sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'PENDING', 'EXCEPTION', 'NOT_APPLICABLE', name='compliancestatus'),
               server_default=sa.text("'compliant'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_application_reminders_id'), table_name='application_reminders')
    op.drop_table('application_reminders')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_priority'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_type'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###