# """add impact column

# Revision ID: 58c105efb762
# Revises: be2c37d28dbf
# Create Date: 2026-03-25 10:25:59.192660+00:00

# """
# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision = '58c105efb762'
# down_revision = 'be2c37d28dbf'
# branch_labels = None
# depends_on = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('application_reminders',
#     sa.Column('id', sa.Integer(), nullable=False),
#     sa.Column('application_id', sa.Integer(), nullable=False),
#     sa.Column('owner_id', sa.Integer(), nullable=True),
#     sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=False),
#     sa.Column('reminder_type', sa.String(length=50), nullable=True),
#     sa.Column('notes', sa.Text(), nullable=True),
#     sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
#     sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
#     sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
#     sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
#     sa.PrimaryKeyConstraint('id')
#     )
#     op.create_index(op.f('ix_application_reminders_id'), 'application_reminders', ['id'], unique=False)
#     op.alter_column('activity_logs', 'priority',
#                existing_type=sa.VARCHAR(length=50),
#                server_default=None,
#                existing_nullable=False)
#     op.alter_column('activity_logs', 'extra_data',
#                existing_type=postgresql.JSONB(astext_type=sa.Text()),
#                type_=sa.JSON(),
#                existing_nullable=True)
#     op.alter_column('activity_logs', 'tags',
#                existing_type=postgresql.JSONB(astext_type=sa.Text()),
#                type_=sa.JSON(),
#                existing_nullable=True)
#     op.alter_column('activity_logs', 'status',
#                existing_type=sa.VARCHAR(length=50),
#                server_default=None,
#                existing_nullable=True)
#     op.alter_column('activity_logs', 'is_read',
#                existing_type=sa.BOOLEAN(),
#                server_default=None,
#                existing_nullable=True)
#     op.alter_column('activity_logs', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                server_default=None,
#                existing_nullable=False)
#     op.alter_column('activity_logs', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                server_default=None,
#                existing_nullable=False)
#     op.drop_index('ix_activity_logs_created_at', table_name='activity_logs')
#     op.create_table_comment(
#         'activity_logs',
#         'Activity log for system-wide event tracking and audit trail',
#         existing_comment=None,
#         schema=None
#     )
#     op.alter_column('users', 'privilege_level',
#                existing_type=sa.VARCHAR(length=50),
#                server_default=None,
#                existing_nullable=False)
#     op.alter_column('users', 'clearance_level',
#                existing_type=sa.VARCHAR(length=50),
#                server_default=None,
#                existing_nullable=False)
#     op.alter_column('vendor_certificates', 'status',
#                existing_type=sa.VARCHAR(length=20),
#                server_default=None,
#                type_=sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'PENDING', 'EXCEPTION', 'NOT_APPLICABLE', name='compliancestatus'),
#                existing_nullable=False)
#     op.alter_column('vendor_certificates', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                server_default=None,
#                nullable=False)
#     op.alter_column('vendor_certificates', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                server_default=None,
#                nullable=False)
#     op.drop_index('idx_vendor_certificates_application_id', table_name='vendor_certificates')
#     op.drop_index('idx_vendor_certificates_expiry_date', table_name='vendor_certificates')
#     op.drop_index('idx_vendor_certificates_status', table_name='vendor_certificates')
#     op.drop_index('idx_vendor_certificates_vendor_id', table_name='vendor_certificates')
#     op.create_index(op.f('ix_vendor_certificates_id'), 'vendor_certificates', ['id'], unique=False)
#     op.drop_constraint('vendor_certificates_vendor_id_fkey', 'vendor_certificates', type_='foreignkey')
#     op.drop_constraint('vendor_certificates_application_id_fkey', 'vendor_certificates', type_='foreignkey')
#     op.create_foreign_key(None, 'vendor_certificates', 'vendors', ['vendor_id'], ['id'])
#     op.create_foreign_key(None, 'vendor_certificates', 'applications', ['application_id'], ['id'])
#     op.alter_column('vendors', 'compliant_controls',
#                existing_type=sa.INTEGER(),
#                server_default=None,
#                existing_nullable=False)
#     op.alter_column('vendors', 'non_compliant_controls',
#                existing_type=sa.INTEGER(),
#                server_default=None,
#                existing_nullable=False)
#     op.add_column('vulnerabilities', sa.Column('impact', sa.Text(), nullable=True))
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_column('vulnerabilities', 'impact')
#     op.alter_column('vendors', 'non_compliant_controls',
#                existing_type=sa.INTEGER(),
#                server_default=sa.text('0'),
#                existing_nullable=False)
#     op.alter_column('vendors', 'compliant_controls',
#                existing_type=sa.INTEGER(),
#                server_default=sa.text('0'),
#                existing_nullable=False)
#     op.drop_constraint(None, 'vendor_certificates', type_='foreignkey')
#     op.drop_constraint(None, 'vendor_certificates', type_='foreignkey')
#     op.create_foreign_key('vendor_certificates_application_id_fkey', 'vendor_certificates', 'applications', ['application_id'], ['id'], ondelete='SET NULL')
#     op.create_foreign_key('vendor_certificates_vendor_id_fkey', 'vendor_certificates', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
#     op.drop_index(op.f('ix_vendor_certificates_id'), table_name='vendor_certificates')
#     op.create_index('idx_vendor_certificates_vendor_id', 'vendor_certificates', ['vendor_id'], unique=False)
#     op.create_index('idx_vendor_certificates_status', 'vendor_certificates', ['status'], unique=False)
#     op.create_index('idx_vendor_certificates_expiry_date', 'vendor_certificates', ['expiry_date'], unique=False)
#     op.create_index('idx_vendor_certificates_application_id', 'vendor_certificates', ['application_id'], unique=False)
#     op.alter_column('vendor_certificates', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                server_default=sa.text('CURRENT_TIMESTAMP'),
#                nullable=True)
#     op.alter_column('vendor_certificates', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                server_default=sa.text('CURRENT_TIMESTAMP'),
#                nullable=True)
#     op.alter_column('vendor_certificates', 'status',
#                existing_type=sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'PENDING', 'EXCEPTION', 'NOT_APPLICABLE', name='compliancestatus'),
#                server_default=sa.text("'compliant'::character varying"),
#                type_=sa.VARCHAR(length=20),
#                existing_nullable=False)
#     op.alter_column('users', 'clearance_level',
#                existing_type=sa.VARCHAR(length=50),
#                server_default=sa.text("'low'::character varying"),
#                existing_nullable=False)
#     op.alter_column('users', 'privilege_level',
#                existing_type=sa.VARCHAR(length=50),
#                server_default=sa.text("'standard'::character varying"),
#                existing_nullable=False)
#     op.drop_table_comment(
#         'activity_logs',
#         existing_comment='Activity log for system-wide event tracking and audit trail',
#         schema=None
#     )
#     op.create_index('ix_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
#     op.alter_column('activity_logs', 'updated_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                server_default=sa.text('CURRENT_TIMESTAMP'),
#                existing_nullable=False)
#     op.alter_column('activity_logs', 'created_at',
#                existing_type=postgresql.TIMESTAMP(timezone=True),
#                server_default=sa.text('CURRENT_TIMESTAMP'),
#                existing_nullable=False)
#     op.alter_column('activity_logs', 'is_read',
#                existing_type=sa.BOOLEAN(),
#                server_default=sa.text('false'),
#                existing_nullable=True)
#     op.alter_column('activity_logs', 'status',
#                existing_type=sa.VARCHAR(length=50),
#                server_default=sa.text("'active'::character varying"),
#                existing_nullable=True)
#     op.alter_column('activity_logs', 'tags',
#                existing_type=sa.JSON(),
#                type_=postgresql.JSONB(astext_type=sa.Text()),
#                existing_nullable=True)
#     op.alter_column('activity_logs', 'extra_data',
#                existing_type=sa.JSON(),
#                type_=postgresql.JSONB(astext_type=sa.Text()),
#                existing_nullable=True)
#     op.alter_column('activity_logs', 'priority',
#                existing_type=sa.VARCHAR(length=50),
#                server_default=sa.text("'medium'::activitypriority"),
#                existing_nullable=False)
#     op.drop_index(op.f('ix_application_reminders_id'), table_name='application_reminders')
#     op.drop_table('application_reminders')
#     # ### end Alembic commands ###


"""add impact column

Revision ID: 58c105efb762
Revises: be2c37d28dbf
Create Date: 2026-03-25 10:25:59.192660+00:00
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '58c105efb762'
down_revision = 'be2c37d28dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'vulnerabilities',
        sa.Column('impact', sa.Text(), nullable=True)
    )


def downgrade() -> None:
    op.drop_column('vulnerabilities', 'impact')